POST http://localhost:3000/user/signup 
Content-Type: application/json

{
    "name": "Karen",
    "email": "ka@email.com",
    "password": "minhaSenha123",
    "role": "ADMIN"
}

### 

POST http://localhost:3000/user/login 
Content-Type: application/json

{
    "email": "ka@email.com",
    "password": "minhaSenha123"

}

###

POST http://localhost:3000/admin/bands 
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg1OTM2OGQ5LWVjMjgtNDE2MS05YjRmLTRjYzVlZTIzOTEwNiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY0NzYzNjE0OCwiZXhwIjoxNjQ3NzIyNTQ4fQ.VhrTKherTR36ZFjeWqzrqvDrjCr9n8Uyp9oLesRU7jM

{
    "name": "The Strokes",
    "music_genre": "Indie Rock",
    "responsible": "Julian Casablancas"
}