POST http://localhost:3000/user/signup 
Content-Type: application/json

{
    "name": "Melissa",
    "email": "mel@email.com",
    "password": "minhaSenha123",
    "role": "NORMAL"
}

### 

POST http://localhost:3000/user/login 
Content-Type: application/json

{
    "email": "ka@email.com",
    "password": "minhaSenha123"

}

###

POST http://localhost:3000/admin/bands 
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg1OTM2OGQ5LWVjMjgtNDE2MS05YjRmLTRjYzVlZTIzOTEwNiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY0NzYzNjE0OCwiZXhwIjoxNjQ3NzIyNTQ4fQ.VhrTKherTR36ZFjeWqzrqvDrjCr9n8Uyp9oLesRU7jM

{
    "name": "Franz Ferdinand",
    "music_genre": "Indie Rock",
    "responsible": "Alex Kapranos"
}

###

GET http://localhost:3000/admin/band/02108654-762b-4b39-9eed-978e6a3a1301 
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg1OTM2OGQ5LWVjMjgtNDE2MS05YjRmLTRjYzVlZTIzOTEwNiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY0NzcyNTA0OSwiZXhwIjoxNjQ3ODExNDQ5fQ.EoKA694fxvRnLhWtaSx8r-Sw_Iob3xPD9T4Sw8jOA3M

###

POST http://localhost:3000/show/register 
Content-Type: application/json

{
    "band_id": "02108654-762b-4b39-9eed-978e6a3a1301",
    "week_day": "DOMINGO",
    "start_time": "21",
    "end_time": "23"
}